"use strict";
let userName;
userName = "Vamsy Kiran";
console.log("Hello " + userName);
let age;
age = 67;
let isEligibleToVote;
isEligibleToVote = age >= 18;
console.log(`Hai ${userName}! You are ${age} years old and hence you ${isEligibleToVote ? "can vote" : "cannot vote"}.`);
const sum = function (a, b) {
    return a + b;
};
console.log(sum(10, 56));
let x;
x = "Vamsy";
console.log(`${x} is a ${typeof x}`);
x = 45;
console.log(`${x} is a ${typeof x}`);
x = false;
console.log(`${x} is a ${typeof x}`);
